[package]
name = "rsgen-avro"
version = "0.1.0"
authors = ["lerouxrgd <leroux.rgd@gmail.com>"]

[dependencies]
failure = "0.1.2"
failure_derive = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
avro-rs = "^0.4"
tera = "0.11"
heck = "0.3.0"
lazy_static = "1.1.0"
docopt = "1"
