[package]
name = "rsgen-avro"
version = "0.1.0"
authors = ["lerouxrgd <leroux.rgd@gmail.com>"]

[dependencies]
avro-rs = "^0.6"
by_address = "1.0.4"
docopt = "1"
failure = "0.1.2"
failure_derive = "0.1.2"
heck = "0.3.0"
lazy_static = "1.1.0"
matches = "0.1.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "0.11"

[dev-dependencies]
gag = "0.1.10"