[package]
name = "rsgen-avro"
version = "0.2.0"
authors = ["lerouxrgd <leroux.rgd@gmail.com>"]
description = "Command line and library for generating Rust types from Avro schemas"
keywords = ["avro", "code-generation", "serde"]
repository = "https://github.com/lerouxrgd/rsgen-avro"
license = "MIT"
readme = "README.md"

[dependencies]
avro-rs = "^0.6"
by_address = "1.0.4"
docopt = "1"
failure = "0.1.3"
heck = "0.3.0"
lazy_static = "1.1.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
tera = "0.11"

[dev-dependencies]
gag = "0.1.10"
matches = "0.1.8"